# Nome do nosso fluxo de trabalho de compilação
name: Buildozer Android APK

# Gatilho: Este fluxo de trabalho rodará toda vez que
# você fizer um 'push' para o branch 'main'
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    # Usando um ambiente comprovadamente estável
    runs-on: ubuntu-22.04

    steps:
      # Passo 1: Baixar o seu código do repositório para a máquina virtual
      - name: Checkout
        uses: actions/checkout@v4

      # NOVO PASSO 2: Configurar e forçar o uso do Python 3.11
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Passo 3: Instalar as dependências do sistema
      - name: Set up Buildozer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          git \
          zip \
          unzip \
          python3-pip \
          python3-venv \
          libffi-dev \
          libssl-dev \
          autoconf \
          autogen \
          automake \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libsndfile1-dev \
          libgstreamer1.0-dev \
          libunwind-dev \
          libgstreamer-plugins-base1.0-dev

      # Passo 4: Instalar as ferramentas Python necessárias
      - name: Install required Python tools
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install setuptools buildozer cython

      # Passo 5: Executar a compilação do Buildozer
      - name: Build with Buildozer
        run: |
          source .venv/bin/activate
          buildozer -v android debug

      # Passo 6: Fazer o upload do APK gerado como um "artefato" (se a compilação tiver SUCESSO)
      - name: Upload APK Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: edmundoapp-apk
          path: bin/*.apk
      
      # Passo 7: Fazer o upload do LOG COMPLETO como um "artefato" (se a compilação FALHAR)
      - name: Upload Log Artifact on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: buildozer-log
          path: .buildozer/logs/buildozer.log
