name: Buildozer Android APK (Stable) 

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    # Usando a versão de suporte de longo prazo mais antiga e estável do Ubuntu
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      # Forçando o uso do Python 3.9, uma versão super estável para compilação Kivy
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Instalando dependências do sistema para o Ubuntu 20.04
      - name: Set up Buildozer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          git \
          zip \
          unzip \
          build-essential \
          python3-pip \
          python3-venv \
          libffi-dev \
          libssl-dev \
          autoconf \
          autogen \
          automake \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libsndfile1-dev \
          libgstreamer1.0-dev \
          libunwind-dev \
          libgstreamer-plugins-base1.0-dev

      # Instalando as ferramentas Python
      - name: Install required Python tools
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install "cython<3.0" setuptools buildozer

      # Compilando com o Buildozer
      - name: Build with Buildozer
        run: |
          source .venv/bin/activate
          buildozer -v android debug

      # Fazendo o upload do APK
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: edmundoapp-apk
          path: bin/*.apk
